services:
  - type: worker
    name: orb-smp-bot
    runtime: node
    plan: starter
    branch: main
    buildCommand: npm install && node deploy-commands.js
    startCommand: node index.js
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        value: "1529395557175660686"
      - key: GUILD_ID
        value: "1345829900606771250"
      - key: TICKET_CATEGORY_ID
        value: "1529393937171746918"
      - key: SUPPORT_ROLE_ID
        value: "1529084117906624542"
